"""Launch demo (docs/PRODUCT_SPEC.md section 13), recorded in the INSTALLED app of the test harness: only what the app does today.

Runs inside the harness container, on a fresh `up` (it replaces the harness's `vendas` Bot with one made from the template):
  docker compose -f tests/harness/compose.yaml exec -T hermes python /root/.hermes/plugins/luvebot/tests/demo/demo_90s.py
Output in /fixtures/demo (on the host: /tmp/luvebot-harness/demo):
  app.webm            the app, recorded by Playwright (recordVideo), steps 1 to 7
  vinheta-fecho.webm  step 8, a CLOSING VIGNETTE generated by this script after the app video: it is NOT an app screen
  demo.log            one line per step: OK, LACUNA (a gap the app has today, never faked) or PREPARO (harness wiring, not product)
Only the model is fake (tests/harness/fake_openai.py, the t119 demo scenarios). Every product action is a click in the real UI;
PREPARO lines are the few things a person would do outside LuveBot (point a Bot at a model provider) or that only seed the demo.
"""
import re
import sqlite3
import sys
import time
from pathlib import Path

from playwright.sync_api import expect, sync_playwright

sys.path.insert(0, '/harness')
from support import DASHBOARD, STATE, credentials, ready  # noqa: E402

PREFIX = '/api/plugins/luvebot'
ROOT = Path('/root/.hermes/plugins/luvebot')
HOME = Path('/root/.hermes')
OUT = STATE / 'demo'
SIZE = {'width': 1440, 'height': 900}
FAKE = 'http://fake-openai:8000/v1'
TEMPLATES = (('Chefe de Gabinete', 'chief-of-staff'), ('Vendas', 'vendas'), ('Engenheiro Dev', 'dev'))
ROOM_TEXT = '@Vendas follow-ups dos leads de ontem; @Dev reproduza o bug do cliente X.'
DRAFTS = 9  # 8 approved in one batch + 1 denied with a reason
UI, LIVE = 15_000, 90_000  # ms: a UI reaction; a Bot's turn through Hermes
LOG = []


def log(kind, step, text):
    line = f'{time.strftime("%H:%M:%S")} {kind:8s} passo {step}: {text}'
    LOG.append(line)
    print(line, flush=True)


def pause(page, ms=1200):
    page.wait_for_timeout(ms)  # time for a viewer to read the screen; never used to wait for the app


# ---- harness wiring through Hermes's and LuveBot's own routes (same calls as tests/invariants) ----
def csrf(context):
    return context.request.get(DASHBOARD + PREFIX + '/session').json()['csrf']


def api(context, method, path, body=None, plugin=True):
    url = DASHBOARD + (PREFIX if plugin else '') + path
    headers = {'X-LuveBot-CSRF': csrf(context)} if plugin and method != 'GET' else {}
    response = context.request.fetch(url, method=method, data=body, headers=headers)
    assert response.status < 300, f'{method} {path}: {response.status} {response.text()[:300]}'
    return response.json() if response.text() else {}


def wait_for(predicate, timeout, what):
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        found = predicate()
        if found:
            return found
        time.sleep(1)
    raise TimeoutError(f'timed out waiting for {what}')


def wait_served(name, timeout=120):
    """The multiplexed gateway reloads a profile's plugins only once it serves it (tests/invariants/test_hook.py wait_served)."""
    from gateway.control_socket import reload_gateway_plugins
    wait_for(lambda: (reload_gateway_plugins(HOME, profile_home=HOME / 'profiles' / name) or {}).get('reloaded'), timeout,
             f'the gateway to serve {name}')


def drop_harness_vendas(context):
    """The harness entrypoint made a `vendas` profile; the demo makes its own from the Vendas template (same name)."""
    names = [p['name'] for p in context.request.get(DASHBOARD + '/api/profiles').json()['profiles']]
    if 'vendas' in names:
        assert context.request.delete(DASHBOARD + '/api/profiles/vendas').status < 300
        conn = sqlite3.connect(HOME / 'luvebot/luvebot.db')
        conn.execute('DELETE FROM bot_meta WHERE bot=?', ('vendas',))
        conn.commit()
        conn.close()
        log('PREPARO', 0, 'perfil vendas do harness removido pela rota do Hermes, para o template Vendas criar o seu')


def point_at_fake_model(context, name, kanban=False):
    """What a person does in Hermes to pick a model provider; here the provider is the harness's fake model, with the same
    config the harness gives its own profiles (tests/harness/entrypoint.py). Dev also gets Hermes's `kanban` toolset."""
    for key, value in (('OPENAI_BASE_URL', FAKE), ('OPENAI_API_KEY', 'harness')):
        api(context, 'PUT', '/api/env', {'key': key, 'value': value, 'profile': name}, plugin=False)
    api(context, 'PUT', '/api/config', {'profile': name, 'config': {
        'model': {'default': 'fake-harness', 'provider': 'custom', 'base_url': FAKE},
        'terminal': {'backend': 'local'}, 'approvals': {'mode': 'manual', 'timeout': 180},
        'platform_toolsets': {'api_server': ['terminal', 'kanban'] if kanban else ['terminal']}}}, plugin=False)
    wait_served(name)
    log('PREPARO', 2, f'{name}: provedor do modelo apontado para o modelo falso do harness (rotas /api/env e /api/config do Hermes)'
        + (', toolset kanban ligado' if kanban else ''))


# ---- the UI ----
def open_luvebot(page):
    page.goto(DASHBOARD + '/')
    page.locator('aside[aria-label="sidebar"]').wait_for(timeout=60_000)
    page.wait_for_function('() => !document.querySelector(\'[aria-label="Carregando bots"]\')', timeout=60_000)


def sidebar_bot(page, pattern):
    return page.locator('aside[aria-label="sidebar"] button[aria-pressed]').filter(has_text=re.compile(pattern, re.I)).first


def rail(page, label):
    page.get_by_role('navigation', name='Navegação Principal').get_by_role('button', name=re.compile(f'^{label}')).click()


def step1_home(page):
    open_luvebot(page)
    expect(page.locator('aside[aria-label="sidebar"]')).to_be_visible()
    log('OK', 1, 'o dashboard do Hermes abre direto no LuveBot (tab.override "/")')
    log('LACUNA', 1, 'o git clone não aparece: no harness o plugin é montado em /root/.hermes/plugins/luvebot; '
        'fora dele, quem liga o plugin é scripts/install.sh')
    pause(page, 2000)


def step2_bots(page, context):
    for label, name in TEMPLATES:
        page.locator('aside[aria-label="sidebar"]').get_by_label(re.compile('Novo Bot')).click()
        dialog = page.get_by_role('dialog')
        expect(dialog).to_contain_text('Passo 1 de 4', timeout=UI)
        dialog.get_by_role('button', name=re.compile(label)).first.click()
        pause(page, 700)
        for step in (2, 3):
            dialog.get_by_role('button', name='Avançar').click()
            expect(dialog).to_contain_text(f'Passo {step + 1} de 4', timeout=UI)
        # the model the harness's Hermes accepts in the wizard (tests/e2e/test_gate2.py); point_at_fake_model swaps the provider
        dialog.get_by_placeholder('claude-sonnet-5-5').fill('anthropic/claude-sonnet-4')
        with page.expect_response(lambda r: r.url.endswith(PREFIX + '/bots') and r.request.method == 'POST', timeout=120_000) as made:
            dialog.get_by_role('button', name='Criar Bot').click()
        assert made.value.status == 201, made.value.text()
        expect(dialog.get_by_test_id('bot-presentation')).to_contain_text('Bot criado com sucesso', timeout=UI)
        log('OK', 2, f'Bot {name} criado pelo template "{label}" no assistente (perfil real do Hermes)')
        # before the introduction (a real model run): the Bot must already talk to the harness's model
        point_at_fake_model(context, name, kanban=name == 'dev')
        intro = dialog.get_by_test_id('bot-introduction')
        intro.get_by_role('button', name='Pedir que o Bot se apresente').click(timeout=LIVE)  # the click confirms the cost
        expect(dialog.get_by_test_id('bot-introduction-answer')).to_contain_text(f'Oi, eu sou {label}', timeout=LIVE)
        log('OK', 2, f'{name} se apresenta de verdade (POST /bots/{name}/introduction, uma execução real no Hermes)')
        pause(page, 2500)
        dialog.get_by_role('button', name='Iniciar com este Bot').click()
        expect(dialog).to_have_count(0, timeout=UI)


def step3_room(page):
    page.locator('aside[aria-label="sidebar"]').get_by_label('Nova sala').click()
    dialog = page.get_by_role('dialog')
    dialog.locator('#create-room-name-input').fill('Lançamento')
    for handle in ('@vendas', '@dev'):
        dialog.locator('button[aria-pressed]').filter(has_text=handle).first.click()
    pause(page, 700)
    dialog.get_by_role('button', name='Criar Sala').click()
    expect(dialog).to_have_count(0, timeout=60_000)  # the new room opens (index.tsx setSelectedRoomId)
    page.get_by_label('Mensagem', exact=True).fill(ROOM_TEXT)
    page.get_by_role('button', name='Enviar').click()  # a click, not Enter: Enter would pick an open mention suggestion
    page.get_by_role('dialog').get_by_role('button', name='Confirmar e Enviar').click()  # two @: cost confirmation
    expect(page.get_by_text('separo os 8 leads de ontem')).to_be_visible(timeout=LIVE)
    expect(page.get_by_text('Vou reproduzir o bug do cliente X')).to_be_visible(timeout=LIVE)
    log('OK', 3, 'na sala, @Vendas e @Dev recebem cada um a sua parte e respondem (Group Chat nativo do Hermes)')
    pause(page, 2500)


def step4_work_panel(page):
    sidebar_bot(page, r'Engenheiro Dev|\bdev\b').click()
    send(page, 'Dev, reproduza o bug do cliente X no terminal.')
    steps = page.locator('button.lb-steps-toggle').filter(has_text='terminal').first
    steps.wait_for(timeout=LIVE)
    if steps.get_attribute('aria-expanded') == 'false':
        steps.click()
    panel = page.locator('[aria-label="Painel de trabalho"]')
    if not panel.is_visible():
        page.get_by_role('button', name='Mostrar painel de trabalho').click()
    panel.get_by_role('tab', name='Terminal').click()
    expect(panel.get_by_role('tabpanel')).to_contain_text('pedidos.js:88', timeout=LIVE)
    log('OK', 4, 'painel de trabalho mostra a ferramenta terminal ao vivo, com a saída na aba Terminal')
    expect(page.get_by_text('Reproduzi: o pedido 4812').first).to_be_visible(timeout=LIVE)
    panel.get_by_role('tab', name='Atividade').click()
    pause(page, 1500)
    log('LACUNA', 4, 'subagentes não aparecem no harness: a conversa já desenha subagent.* (SubagentCard), mas o modelo falso não '
        'delega (o api_server do harness só tem terminal e kanban)')


def send(page, text):
    box = page.get_by_label('Mensagem', exact=True)
    box.wait_for(timeout=UI)
    box.fill(text)
    box.press('Enter')


def step5_approvals(page, context):
    def draft(n):  # one session per run, like tests/invariants/test_approvals.py ask_run
        sid = api(context, 'POST', '/bots/vendas/sessions', {})['session']['id']
        return api(context, 'POST', '/bots/vendas/runs', {'input': f'Prepare o follow-up do lead {n}.', 'session_id': sid})['run']['id']
    runs = [draft(n) for n in range(1, DRAFTS + 1)]
    log('PREPARO', 5, f'{DRAFTS} rascunhos de follow-up pedidos à Vendas pela rota de runs do LuveBot (a mesma do chat)')
    pending = lambda: [a for a in api(context, 'GET', '/approvals?status=pending&limit=100')['approvals'] if a['run_id'] in runs]
    wait_for(lambda: len(pending()) == DRAFTS, 120, f'{DRAFTS} pending approvals')
    rail(page, 'Aprovações')
    page.get_by_role('button', name='Atualizar aprovações').click()
    cards = page.locator('[data-testid^="approval-card-"]')
    expect(cards).to_have_count(DRAFTS, timeout=UI)
    pause(page, 1500)
    page.get_by_label('Selecionar todas as pendentes').check()
    cards.last.get_by_role('checkbox').uncheck()  # the one that will be denied with a reason
    page.get_by_role('button', name='Permitir selecionados (uma vez)').click()
    page.get_by_role('button', name='Confirmar decisão em lote').click()
    expect(cards.filter(has=page.get_by_role('button', name='Negar…'))).to_have_count(1, timeout=60_000)
    log('OK', 5, f'{DRAFTS - 1} rascunhos aprovados em lote na caixa de aprovações')
    pause(page, 1200)
    cards.filter(has=page.get_by_role('button', name='Negar…')).get_by_role('button', name='Negar…').click()
    page.locator('#deny-reason-input').fill('Esse lead pediu para não receber mais e-mails.')
    pause(page, 900)
    page.get_by_role('button', name='Confirmar negação').click()
    wait_for(lambda: not pending(), 60, 'no pending approval left')
    log('OK', 5, '1 rascunho negado com motivo')
    log('LACUNA', 5, 'o Bot não corrige: o motivo fica no LuveBot e na auditoria, não chega ao Bot (reason_delivered=False) (b3, Brasa)')
    pause(page, 1500)


def step6_handoff(page, context):
    sidebar_bot(page, r'Engenheiro Dev|\bdev\b').click()
    send(page, 'Passe a correção para a Vendas avisar o cliente X.')
    expect(page.get_by_text('está com a Vendas no Kanban').first).to_be_visible(timeout=LIVE)
    edge = lambda: next((e for e in api(context, 'GET', '/map?window=7d').get('edges', []) if e['from'] == 'dev' and e['to'] == 'vendas'), None)
    wait_for(lambda: (edge() or {}).get('live'), 60, 'the live dev -> vendas edge')  # the watcher turns the Kanban task into a handoff
    rail(page, 'Mapa')
    page.locator('#tab-map-visual').click()
    pause(page, 3000)
    page.locator('#tab-map-accessible').click()
    expect(page.get_by_test_id('map-handoff-item').filter(has_text='Handoff ao vivo').first).to_be_visible(timeout=UI)
    log('OK', 6, 'Dev cria a tarefa da Vendas pelo Kanban do Hermes; o Mapa mostra a aresta dev -> vendas acesa')
    pause(page, 1500)


def step7_ceiling(page):
    page.keyboard.press('Control+k')
    page.get_by_placeholder('Digite para buscar mensagens, bots, salas, rotinas ou ações...').fill('Custos')
    page.get_by_text('Ver Custos e Orçamento').first.click()
    page.get_by_role('button', name='Tetos e Limites').click()
    page.get_by_test_id('btn-new-limit').click()
    page.locator('select').filter(has=page.locator('option[value="routine"]')).select_option('bot')
    page.get_by_placeholder('ex: vendas, rotina-1').fill('vendas')
    page.get_by_test_id('input-limit-amount').fill('0')
    pause(page, 900)
    page.get_by_test_id('btn-save-limit').click()
    page.get_by_role('button', name=re.compile('Bots Pausados')).click()
    expect(page.get_by_test_id('paused-bot-vendas')).to_be_visible(timeout=60_000)
    log('OK', 7, 'teto de US$ 0,00 para a Vendas: o Bot é pausado na hora e Custos lista o que foi pausado')
    pause(page, 2500)


VIGNETTE = """<!doctype html><html><head><meta charset="utf-8"><title>Vinheta de fecho (não é tela do app)</title>
<!-- VINHETA gerada por tests/demo/demo_90s.py depois do vídeo do app. Não é uma tela do LuveBot. -->
<style>html,body{margin:0;height:100%;background:#0b0f19;color:#fff;font-family:Inter,system-ui,sans-serif}
main{height:100%;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:28px;text-align:center}
img{width:420px;opacity:0;animation:in .8s .2s ease-out forwards}p{margin:0;font-size:40px;font-weight:700;letter-spacing:-.02em;opacity:0;animation:in .8s 1s ease-out forwards}
@keyframes in{from{opacity:0;transform:translateY(12px)}to{opacity:1;transform:none}}
@media (prefers-reduced-motion:reduce){img,p{animation:none;opacity:1}}</style></head>
<body><main><img src="data:image/svg+xml;base64,{logo}" alt="LuveBot"><p>Seus Bots, seu servidor.<br>LuveBot, by Luve.</p></main></body></html>"""


def step8_vignette(browser):
    import base64
    logo = base64.b64encode((ROOT / 'docs/images/logo/luvebot-wordmark-white.svg').read_bytes()).decode()
    context = browser.new_context(viewport=SIZE, record_video_dir=str(OUT / 'vinheta'), record_video_size=SIZE)
    page = context.new_page()
    page.set_content(VIGNETTE.replace('{logo}', logo))
    page.wait_for_timeout(4500)
    video = page.video
    context.close()
    Path(video.path()).rename(OUT / 'vinheta-fecho.webm')
    log('VINHETA', 8, '"Seus Bots, seu servidor. LuveBot, by Luve." gerada pelo script depois do vídeo do app, em '
        'vinheta-fecho.webm: é vinheta, não é tela do app')


def main():
    ready()
    OUT.mkdir(parents=True, exist_ok=True)
    creds = credentials()
    with sync_playwright() as playwright:
        browser = playwright.chromium.launch(headless=True, args=['--no-sandbox'])
        login = browser.new_context(locale='pt-BR')
        response = login.request.post(DASHBOARD + '/auth/password-login', data={  # ONE login: Hermes answers 429 to more
            'provider': 'basic', 'username': creds['username'], 'password': creds['password'], 'next': '/'})
        assert response.status == 200 and response.json()['ok'] is True
        state = login.storage_state()
        login.close()
        context = browser.new_context(viewport=SIZE, storage_state=state, color_scheme='dark', locale='pt-BR',
                                      record_video_dir=str(OUT / 'app'), record_video_size=SIZE)
        assert context.request.put(DASHBOARD + '/api/dashboard/theme', data={'name': 'luve'}).status == 200
        themes = HOME / 'dashboard-themes'
        themes.mkdir(parents=True, exist_ok=True)
        (themes / 'luve.yaml').write_bytes((ROOT / 'theme/luve.yaml').read_bytes())  # what scripts/install.sh does
        drop_harness_vendas(context)
        page = context.new_page()
        failed = None
        try:
            step1_home(page)
            step2_bots(page, context)
            step3_room(page)
            step4_work_panel(page)
            step5_approvals(page, context)
            step6_handoff(page, context)
            step7_ceiling(page)
        except Exception as error:  # the video up to the failure is kept; the log says where it stopped
            failed = error
            page.screenshot(path=str(OUT / 'falha.png'))
            log('FALHOU', '-', f'{type(error).__name__}: {str(error)[:400]}')
        video = page.video
        context.close()
        Path(video.path()).rename(OUT / 'app.webm')
        if failed is None:
            step8_vignette(browser)
        browser.close()
    (OUT / 'demo.log').write_text('\n'.join(LOG) + '\n')
    if failed is not None:
        raise SystemExit(1)


if __name__ == '__main__':
    main()
